INSERT INTO STUDENTS(STUDENT_ID, ADDRESS_ID, NAME, SURNAME, EMAIL, PHONE) VALUES(1, 1, 'Jozef', 'Jozefowicz', 'jozek@test.pl', '111111111');
INSERT INTO STUDENTS(STUDENT_ID, ADDRESS_ID, NAME, SURNAME, EMAIL, PHONE) VALUES(2, 2, 'Zenon', 'Baleron', 'jozek@test.pl', '111111111');
INSERT INTO STUDENTS(STUDENT_ID, ADDRESS_ID, NAME, SURNAME, EMAIL, PHONE) VALUES(3, 3, 'Tadeusz', 'Pan', 'jozek@test.pl', '111111111');

INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES (1, '02-583', 'Warszawa', 'Woloska', '9');
INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES (2, '02-641', 'Warszawa', 'Woronicza', '11');
INSERT INTO ADDRESSES(ADDRESS_ID, POST_CODE, CITY, STREET, BUILDING_NUMBER) VALUES (3, '02-999', 'Warszawa', 'Ostrobramska', '1');

INSERT INTO BOOKS(BOOK_ID, STUDENT_ID, TITLE, AUTHOR) VALUES(1, 1, 'Spring w akcji', 'Stefan');
INSERT INTO BOOKS(BOOK_ID, STUDENT_ID, TITLE, AUTHOR) VALUES(2, 1, 'Hibernate w akcji', 'Stefan');

INSERT INTO COURSES(COURSE_ID, NAME) VALUES(1, 'Informatyka');
INSERT INTO COURSES(COURSE_ID, NAME) VALUES(2, 'Matematyka');
INSERT INTO COURSES(COURSE_ID, NAME) VALUES(3, 'Ekonomia');

INSERT INTO STUDENTS_COURSES(STUDENT_ID, COURSE_ID) VALUES(1, 1);
INSERT INTO STUDENTS_COURSES(STUDENT_ID, COURSE_ID) VALUES(1, 2);
INSERT INTO STUDENTS_COURSES(STUDENT_ID, COURSE_ID) VALUES(2, 1);
INSERT INTO STUDENTS_COURSES(STUDENT_ID, COURSE_ID) VALUES(3, 1);
