CREATE SEQUENCE STUDENTS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADDRESSES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BOOKS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE STUDENTS (
  STUDENT_ID INTEGER PRIMARY KEY,
  ADDRESS_ID INTEGER,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255),
  EMAIL VARCHAR(255),
  PHONE VARCHAR(255)
);

CREATE TABLE ADDRESSES (
  ADDRESS_ID INTEGER PRIMARY KEY,
  POST_CODE VARCHAR(255),
  CITY VARCHAR(255),
  STREET VARCHAR(255),
  BUILDING_NUMBER VARCHAR(10)
);

CREATE TABLE BOOKS (
  BOOK_ID INTEGER PRIMARY KEY,
  STUDENT_ID INTEGER,
  TITLE VARCHAR(255),
  AUTHOR VARCHAR(255)
);

CREATE TABLE COURSES (
  COURSE_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE STUDENTS_COURSES (
  COURSE_ID INTEGER,
  STUDENT_ID INTEGER
);

